### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by mattybme** [derekdanderson/createdraftarticlefromcase#2]
It says the repository could not be found when I try and login to a prod instance

**Comment by derekdanderson** [comment]
Should be fixed now.  Try again.

**Comment by derekdanderson** [comment]
This issue was caused by moving away from the branch name "master" and moving to "main".  I updated the deploy link to account for this.

**Comment by mattybme** [comment]
Thanks @derekdanderson it installs now! :)
